name: "Free Disk Space"
description: "Free up disk space on Linux runners by removing unnecessary runtimes and packages"

inputs:
  android:
    description: "Remove Android runtime"
    required: false
    default: "true"
  dotnet:
    description: "Remove .NET runtime"
    required: false
    default: "true"
  haskell:
    description: "Remove Haskell runtime"
    required: false
    default: "true"
  llvm:
    description: "Remove LLVM toolchain"
    required: false
    default: "true"
  php:
    description: "Remove PHP runtime"
    required: false
    default: "true"
  mongodb:
    description: "Remove MongoDB runtime"
    required: false
    default: "true"
  mysql:
    description: "Remove MySQL runtime"
    required: false
    default: "true"
  misc-packages:
    description: "Remove miscellaneous packages (azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri)"
    required: false
    default: "true"
  docker-images:
    description: "Remove Docker images"
    required: false
    default: "true"
  tools-cache:
    description: "Remove image tool cache"
    required: false
    default: "false"
  swap-storage:
    description: "Remove swap storage"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh
      env:
        INPUT_ANDROID: "${{ inputs.android }}"
        INPUT_DOTNET: "${{ inputs.dotnet }}"
        INPUT_HASKELL: "${{ inputs.haskell }}"
        INPUT_LLVM: "${{ inputs.llvm }}"
        INPUT_PHP: "${{ inputs.php }}"
        INPUT_MONGODB: "${{ inputs.mongodb }}"
        INPUT_MYSQL: "${{ inputs.mysql }}"
        INPUT_MISC_PACKAGES: "${{ inputs.misc-packages }}"
        INPUT_DOCKER_IMAGES: "${{ inputs.docker-images }}"
        INPUT_TOOLS_CACHE: "${{ inputs.tools-cache }}"
        INPUT_SWAP_STORAGE: "${{ inputs.swap-storage }}"
      shell: bash
