name: "Free Disk Space"
description: "Free up disk space on Linux runners by removing unnecessary runtimes and packages"

inputs:
  android:
    description: "Remove Android runtime"
    required: false
    default: "true"
  dotnet:
    description: "Remove .NET runtime"
    required: false
    default: "true"
  haskell:
    description: "Remove Haskell runtime"
    required: false
    default: "true"
  llvm:
    description: "Remove LLVM toolchain"
    required: false
    default: "true"
  php:
    description: "Remove PHP runtime"
    required: false
    default: "true"
  mongodb:
    description: "Remove MongoDB runtime"
    required: false
    default: "true"
  mysql:
    description: "Remove MySQL runtime"
    required: false
    default: "true"
  misc-packages:
    description: "Remove miscellaneous packages (azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri)"
    required: false
    default: "true"
  docker-images:
    description: "Remove Docker images"
    required: false
    default: "true"
  tools-cache:
    description: "Remove image tool cache"
    required: false
    default: "false"
  swap-storage:
    description: "Remove swap storage"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - if: ${{ runner.os != 'Linux' }}
      run: |
        echo "::error::This action is only supported on Linux runners."
        exit 0
      shell: bash
    - if: ${{ inputs.android == 'true' }}
      run: sudo rm -rf /usr/local/lib/android
      shell: bash
    - if: ${{ inputs.dotnet == 'true' }}
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
      shell: bash
    - if: ${{ inputs.haskell == 'true' }}
      run: sudo rm -rf /opt/ghc
      shell: bash
    - if: ${{ inputs.llvm == 'true' }}
      run: |
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
      shell: bash
    - if: ${{ inputs.php == 'true' }}
      run: |
        sudo apt-get remove -y '^php[0-9.\\-]*'
        sudo apt-get autoremove -y
        sudo apt-get clean
      shell: bash
    - if: ${{ inputs.mongodb == 'true' }}
      run: |
        sudo apt-get remove -y '^mongodb-.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
      shell: bash
    - if: ${{ inputs.mysql == 'true' }}
      run: |
        sudo apt-get remove -y '^mysql-.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
      shell: bash
    - if: ${{ inputs.misc-packages == 'true' }}
      run: |
        sudo apt-get remove -y \
          azure-cli google-cloud-sdk
          google-chrome-stable firefox
          powershell mono-devel libgl1-mesa-dri
        sudo apt-get autoremove -y
        sudo apt-get clean
      shell: bash
    - if: ${{ inputs.docker-images == 'true' }}
      run: sudo docker image prune -af
      shell: bash
    - if: ${{ inputs.tools-cache == 'true' }}
      run: sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
      shell: bash
    - if: ${{ inputs.swap-storage == 'true' }}
      run: |
        sudo swapoff -a
        sudo rm -f /mnt/swapfile
      shell: bash
