name: 'Setup TemplateMan'
description: "Install TemplateMan CLI"

inputs:
  token:
    description: 'GitHub Token'
    required: true
    default: ''
  version:
    description: 'Setup with specific version'
    required: false
    default: 'latest'
  go-version:
    description: 'Specify Go version'
    required: false
    default: 'stable'

runs:
  using: "composite"
  steps:
    - uses: projectdiscovery/actions/setup/go@v1
      with:
        go-version: '${{ inputs.go-version }}'
    - run: git config --global url."https://${{ inputs.token }}@github.com/".insteadOf https://github.com/
      shell: bash
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-${{ inputs.go-version }}_templateman-${{ inputs.version }}_${{ runner.os }}
        restore-keys: |
          go-${{ inputs.go-version }}_templateman-${{ inputs.version }}_
    - run: $GITHUB_ACTION_PATH/main.sh
      env:
        VERSION: '${{ inputs.version }}'
        GOPRIVATE: 'github.com/projectdiscovery/*'
      shell: bash
