name: 'Nuclei Templates Sync'
description: 'Early nuclei templates synchronize'

inputs:
  token:
    description: 'GitHub Token'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - run: gh auth login --with-token <<< $TOKEN
      env:
        TOKEN: '${{ inputs.token }}'
      shell: bash
    - run: gh workflow -R projectdiscovery/early-templates run repo-sync.yaml --ref main
      shell: bash