name: 'Compatibility Checks'
description: 'Run compatibility checks for Go projects'

inputs:
  go-version:
    description: 'Setup with specific version'
    required: false
    default: ''
  go-version-file:
    description: 'Path to go version file'
    required: false
    default: 'go.mod'
  release-test:
    description: 'Run release test (with goreleaser)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: projectdiscovery/actions/setup/git@v1
    - uses: projectdiscovery/actions/setup/go@v1
      with:
        go-version: '${{ inputs.go-version }}'
        go-version-file: ${{ inputs.go-version == '' && inputs.go-version-file || '' }}
    - name: Get base directory
      id: get-basedir
      run: |
        if [ -f "${{ inputs.go-version-file }}" ]; then
          WORKING_DIR=$(dirname "${{ inputs.go-version-file }}")
        else
          WORKING_DIR="$GITHUB_WORKSPACE"
        fi
        echo "basedir=${WORKING_DIR}" >> $GITHUB_OUTPUT
      shell: bash
    - run: go mod download && go mod verify && go vet ./...
      working-directory: ${{ steps.get-basedir.outputs.basedir }}
      shell: bash
    - name: Checks go.mod Integrity
      run: |
        git diff --exit-code go.mod >/dev/null || {
          echo "::warning::go.mod is out of sync. Pushing changes to the branch."
          git add go.{mod,sum}
          git commit -m "chore(deps): go mod tidy"
          git push origin $GITHUB_REF
        }
      working-directory: ${{ steps.get-basedir.outputs.basedir }}
      shell: bash
    - uses: projectdiscovery/actions/goreleaser@v1
      if: ${{ inputs.release-test == 'true' }}
      with:
        workdir: ${{ steps.get-basedir.outputs.basedir }}
