name: 'GoReleaser'
description: 'Run GoReleaser'

inputs:
  release:
    description: 'Run without snapshot'
    required: false
    default: 'false'
  workdir:
    description: 'Working directory'
    required: false
    default: '.'
  args:
    description: 'Run with arguments'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: projectdiscovery/actions/free-disk-space@v1
      with:
        llvm: 'false'
        php: 'false'
        mongodb: 'false'
        mysql: 'false'
        misc-packages: 'false'
        docker-images: 'false'
        tools-cache: 'false'
    - if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
    - if: runner.os == 'Linux'
      uses: docker/setup-buildx-action@v3
    - uses: goreleaser/goreleaser-action@v6
      with:
        version: 'latest'
        args: release --clean ${{ inputs.release != 'true' && '--snapshot' || '' }} ${{ inputs.args }}
        workdir: '${{ inputs.workdir }}'