name: 'GolangCI Lint'
description: 'Run GolangCI Lint'

inputs:
  version:
    description: 'GolangCI Lint version'
    required: false
    default: 'latest'
  args:
    description: 'Run with arguments'
    required: false
    default: '--timeout=30m'

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/golangci-lint
        key: golangci-lint_${{ runner.os }}
        restore-keys: golangci-lint_
    - uses: golangci/golangci-lint-action@v6
      with:
        version: ${{ inputs.version }}
        args: ${{ inputs.args }}