name: 'Setup Nuclei'
description: "Install Nuclei engine"

inputs:
  version:
    description: 'Setup with specific version ("latest" or in format "vX.Y.Z")'
    required: true
    default: 'latest'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm ci
      shell: bash
      working-directory: '${{ github.action_path }}'
    - uses: actions/github-script@v7
      env:
        INPUT_VERSION: '${{ inputs.version }}'
        NODE_PATH: '${{ github.action_path }}/node_modules'
      with:
        script: |
          const tc = require(require.resolve('@actions/tool-cache', {paths: [process.env.NODE_PATH]}))
          const dl = require(process.env.GITHUB_ACTION_PATH + '/download.js')
          await dl({github, context, core, tc})
