name: 'Setup Nuclei'
description: "Install Nuclei engine"

inputs:
  version:
    description: 'Setup with specific version ("latest" or in format "vX.Y.Z")'
    required: true
    default: 'latest'
  token:
    description: 'GitHub Token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun i
      shell: bash
      working-directory: '${{ github.action_path }}'
    - run: bun main.js
      env:
        INPUT_TOKEN: '${{ inputs.token }}'
        INPUT_VERSION: '${{ inputs.version }}'
      shell: bash
      working-directory: '${{ github.action_path }}'