name: 'Setup Go'
description: 'Run actions/setup-go'

inputs:
  go-version:
    description: 'Setup with specific version'
    required: false
    default: ''
  go-version-file:
    description: 'Path to go version file'
    required: false
    default: 'go.mod'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v6
      with:
        check-latest: true
        go-version: '${{ inputs.go-version }}'
        go-version-file: ${{ inputs.go-version == '' && inputs.go-version-file || '' }}
        cache-dependency-path: '**/go.sum'
